In [10]:
from keras.models import Sequential
from keras.layers import *
import numpy as np


def start(neuron1, neuron2):
    m = Sequential() 
    m.add(Dense(neuron1,input_dim=2, activation='tanh'))
    m.add(Dense(neuron2,input_dim=2, activation='tanh'))
    m.add(Dense(1,activation='sigmoid'))

    X = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
    Y = np.array([[0],[1],[1],[0]],'float32')
    m.compile(optimizer='adam',loss='binary_crossentropy')


    m.fit(X,Y,batch_size=1,epochs=200,verbose=0)
    print(m.predict(X))

    print('Bramka OR')
    X1 = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
    Y1 = np.array([[0],[1],[1],[1]],'float32')

    m.fit(X1,Y1,batch_size=1,epochs=200,verbose=0)
    print(m.predict(X1))

    X2 = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
    Y2 = np.array([[1],[0],[0],[0]],'float32')

    print('Bramka NOR')
    m.fit(X2,Y2,batch_size=1,epochs=200,verbose=0)
    print(m.predict(X2))

    X3 = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
    Y3 = np.array([[0],[0],[0],[1]],'float32')

    print('Bramka AND')
    m.fit(X3,Y3,batch_size=1,epochs=200,verbose=0)
    print(m.predict(X3))

    X4 = np.array([[0,0],[0,1],[1,0],[1,1]],'float32')
    Y4 = np.array([[1],[1],[1],[0]],'float32')

    print('Bramka NAND')
    m.fit(X4,Y4,batch_size=1,epochs=200,verbose=0)
    print(m.predict(X4))




In [13]:
print("Wynik dla architektury 1")
start(5,8)

Wynik dla architektury 1
1/1 [==============================] - 0s 149ms/step
[[0.4437867 ]
 [0.51095176]
 [0.60160565]
 [0.5412515 ]]
Bramka OR
1/1 [==============================] - 0s 117ms/step
[[0.12893698]
 [0.95437986]
 [0.94997495]
 [0.98796374]]
Bramka NOR
1/1 [==============================] - 0s 53ms/step
[[0.84974957]
 [0.03900084]
 [0.05902585]
 [0.00837822]]
Bramka AND
1/1 [==============================] - 0s 60ms/step
[[0.04662193]
 [0.22826184]
 [0.14914171]
 [0.64928997]]
Bramka NAND
1/1 [==============================] - 0s 51ms/step
[[0.8962932 ]
 [0.71501076]
 [0.7917326 ]
 [0.4779765 ]]


In [14]:
print("Wynik dla architektury 2")
start(4,9)

Wynik dla architektury 2
1/1 [==============================] - 0s 188ms/step
[[0.40227708]
 [0.6208054 ]
 [0.589069  ]
 [0.58521664]]
Bramka OR
1/1 [==============================] - 0s 118ms/step
[[0.08151042]
 [0.95852816]
 [0.9677428 ]
 [0.9802237 ]]
Bramka NOR
1/1 [==============================] - 0s 63ms/step
[[0.90438753]
 [0.04395578]
 [0.02556837]
 [0.01264445]]
Bramka AND
1/1 [==============================] - 0s 63ms/step
[[0.06439109]
 [0.12826653]
 [0.1712751 ]
 [0.58346397]]
Bramka NAND
1/1 [==============================] - 0s 63ms/step
[[0.740189  ]
 [0.7110915 ]
 [0.66092956]
 [0.56116843]]
